<a href="https://colab.research.google.com/github/IshanKarn/ML-Projects/blob/main/NumPy_Bootcamp_Graded_Hands_on_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Overview**

Dear Learner, 

Congratulations, you have studied NumPy all the way through the end of this bootcamp!!! This is the final graded hands-on exercise where you will be accomplishing the below mentioned task.

**Author:** Avantika Podar

###Task 1:   

Construct a random 3x28x28 NumPy array called *original* to represent an image and then convert this into into a 1x(3x28x28) array called *flat*. This converts it into a single row of pixels. Next, convert this to a 1D array (flatten the array using flat.flatten()). Print shape of all arrays. You may use the random function to generate the array.



In [17]:
import numpy as np
from numpy import random

In [18]:
original = random.randint(10, size=(3,28,28))
flat = original.reshape(1,3*28*28)
arr_1d = flat.flatten()

In [19]:
print(original.shape)
print(flat.shape)
print(arr_1d.shape)

(3, 28, 28)
(1, 2352)
(2352,)


In [37]:
# extra
print(original)

[[[7 2 3 ... 6 3 4]
  [8 9 4 ... 1 5 8]
  [8 7 4 ... 6 2 0]
  ...
  [7 4 2 ... 3 2 3]
  [3 7 9 ... 7 0 5]
  [5 5 8 ... 1 4 9]]

 [[4 6 6 ... 8 9 3]
  [6 9 4 ... 9 9 7]
  [8 8 6 ... 2 8 4]
  ...
  [9 5 0 ... 6 2 9]
  [9 2 9 ... 6 8 7]
  [2 7 0 ... 3 8 7]]

 [[0 1 8 ... 6 3 0]
  [9 7 3 ... 0 0 6]
  [9 5 4 ... 0 0 4]
  ...
  [1 2 4 ... 8 8 2]
  [2 0 0 ... 7 2 3]
  [5 7 6 ... 3 2 7]]]


### Task 2: Print out the following: 
  * dimension of the arrays.
  * memory address of the arrays (pointer).
  * shape of the arrays.
  * data types of the arrays. 




In [20]:
# Dimensions
print(original.ndim)
print(flat.ndim)
print(arr_1d.ndim)

3
2
1


In [28]:
# Memory address
print(id(original))
print(original.data) 
print(original.__array_interface__['data'][0]) # memory address (pointer)

print(id(flat))
print(flat.data) 
print(flat.__array_interface__['data'][0]) # memory address (pointer)

print(arr_1d.__array_interface__['data'][0])

140247647737376
93936167919616
140247647738336
93936167919616
93936165777408


In [29]:
# Shape
print(original.shape)
print(flat.shape)
print(arr_1d.shape)

(3, 28, 28)
(1, 2352)
(2352,)


In [32]:
# Datatypes
print(original.dtype)
print(flat.dtype)
print(arr_1d.dtype)

int64
int64
int64


### Task 3: 
Construct a new array which is a negative of the *original* array, i.e, all elements are negative of those in the *original* array. Print the new array. Add the original and new arrays. Print the result. 

In [36]:
negative_original = original * -1
print(negative_original)

[[[-7 -2 -3 ... -6 -3 -4]
  [-8 -9 -4 ... -1 -5 -8]
  [-8 -7 -4 ... -6 -2  0]
  ...
  [-7 -4 -2 ... -3 -2 -3]
  [-3 -7 -9 ... -7  0 -5]
  [-5 -5 -8 ... -1 -4 -9]]

 [[-4 -6 -6 ... -8 -9 -3]
  [-6 -9 -4 ... -9 -9 -7]
  [-8 -8 -6 ... -2 -8 -4]
  ...
  [-9 -5  0 ... -6 -2 -9]
  [-9 -2 -9 ... -6 -8 -7]
  [-2 -7  0 ... -3 -8 -7]]

 [[ 0 -1 -8 ... -6 -3  0]
  [-9 -7 -3 ...  0  0 -6]
  [-9 -5 -4 ...  0  0 -4]
  ...
  [-1 -2 -4 ... -8 -8 -2]
  [-2  0  0 ... -7 -2 -3]
  [-5 -7 -6 ... -3 -2 -7]]]


In [42]:
arr_add_result = original + negative_original
print(arr_add_result)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


###Task 4

A 3x28x28 basically means 28x28 matrices repeated three times. How would you access the first 10 elements of the 2nd row of the second 28x28 matrix? Consider the original array for this. Print the elements.

In [47]:
print(original[1][1, 0:10])

[6 9 4 6 1 0 4 6 1 0]


### Task 5 
A 3x28x28 image means 3 channels of Red, Green, or Blue (Popularly known as RGB image). Each color channel has a height and width, which is 28X28 in this case. The entire picture can represented through this method. Print the shape of the Blue pixel matrix and its first 3 rows.

In [53]:
# Shape of Blue pixel matrix
print(original[2].shape)

# Shape of first 3 rows of blue pixel matrix
print(original[2][:3].shape)

(28, 28)
(3, 28)


### Task 6 
Create a 1 dimensional numpy array of the first 50 even numbers. Convert this to a 10x5 numpy array and print its transpose. 

In [66]:
even_arr_1d = np.arange(2, 102, 2)
reshaped_arr = even_arr_1d.reshape(10, 5)
print(reshaped_arr.T)

[[  2  12  22  32  42  52  62  72  82  92]
 [  4  14  24  34  44  54  64  74  84  94]
 [  6  16  26  36  46  56  66  76  86  96]
 [  8  18  28  38  48  58  68  78  88  98]
 [ 10  20  30  40  50  60  70  80  90 100]]


###Task 7 
Consider the 10x5 array created in Task 6. Find the mean of each row and column. You may use in built functions or write your own code.

In [68]:
reshaped_arr

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [72]:
# Mean of each row (top to bottom) of 10x5 array
print("Row-wise mean:", reshaped_arr.mean(axis = 1))

# Mean of each column (left to right) of 10x5 array
print("Column-wise mean:", reshaped_arr.mean(axis = 0))

Row-wise mean: [ 6. 16. 26. 36. 46. 56. 66. 76. 86. 96.]
Column-wise mean: [47. 49. 51. 53. 55.]


In [81]:
# User defined function to calculate row-wise means of a 2-D array
def mean_rows(arr_2d):
  rowise_means = []
  for row in arr_2d:
    sum = 0
    for i in row:
      sum += i
    rowise_means.append(sum/len(row))
  return rowise_means

# User defined function to calculate column-wise means of a 2-D array
def mean_cols(arr_2d):
  colwise_means = []
  for row in arr_2d.T:
    sum = 0
    for i in row:
      sum += i
    colwise_means.append(sum/len(row))
  return colwise_means

# Calculating row-wise and column-wise mean of 10x5 array
print("Row-wise mean:", mean_rows(reshaped_arr))
print("Column-wise mean:", mean_cols(reshaped_arr))

Row-wise mean: [6.0, 16.0, 26.0, 36.0, 46.0, 56.0, 66.0, 76.0, 86.0, 96.0]
Column-wise mean: [47.0, 49.0, 51.0, 53.0, 55.0]


### Task 8
Can we create a 3x3 array of the first 50 even numbers? Why or why not? What are other values of m and n for which mxn dimension is allowed for 50 elements?

No, we cannot create a 3x3 array of first 50 even numbers.

A 3x3 array has 3 rows and 3 columns so it can store 9 values only.

Possible values of dimension must be the numbers whose product is equal to 50.

For 2-D arrays it will be two positive numbers m and n.

Such that, m x n = 50

Since, 10 x 5 = 50 or 5 x 10 = 50

So, possible values of m, n pairs are **10, 5 and 5, 10** for which required mxn dimension is allowed for 50 elements.

---
\
**Code:**


``` python
import numpy as np

arr = np.arange(2, 102, 2)

print(arr.reshape(10, 5)) # m = 10, n = 5 (correct)
print(arr.reshape(5, 10)) # m = 5, n = 10 (correct)
print(arr.reshape(3, 3))  # Raise ValueError (Incorrect)
```

---